DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/2


###
DELETE http://localhost:3001/api/persons/146

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{"name":"bhimchsehetri we",
  "number": "9876"}
