DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/61cdf9d04a57cfe3ab0758f0


###
DELETE http://localhost:3001/api/persons/146

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{"name":"am",
  "number": 98760}
